theme: "hugo-PaperMod"
baseURL: https://louislippens.be
languageCode: en-uk
title: Louis Lippens
paginate: 5
googleAnalytics: G-353SE2Q1DW

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

permalinks:
  post: /:year/:month/:day/:slug/

menu:
  main:
    - name: home
      url: /
      weight: 1
    - name: about
      url: /about/
      weight: 2
    - name: research
      url: /research/
      weight: 3
      
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: >
        Louis Lippens, doctoral researcher in economics and sociology at UGent and VUB."
  author: Louis Lippens
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  defaultTheme: auto
  disableThemeToggle: true
  homeInfoParams:
      Title: "Hello, visitor \U0001F44B"
      Content: >
        Welcome to my personal website. You can read more about me in the eponymous tab or
        discover my (academic) work in one of the other tabs above. Links to my socials are below.
  socialIcons:
      - name: "LinkedIn"
        url: "https://www.linkedin.com/in/louislippens/"
      - name: "Twitter"
        url: "https://twitter.com/LippensLouis"
      - name: "Google Scholar"
        url: "https://scholar.google.com/citations?user=N5hW-KgAAAAJ"
      - name: "ResearchGate"
        url: "https://www.researchgate.net/profile/Louis-Lippens"
  assets:
        favicon: "/favicon.ico"
        favicon16x16:  "/favicon-16x16.png"
        favicon32x32:  "/favicon-32x32.png"
        apple_touch_icon:  "/apple-touch-icon.png"

markup:
  goldmark:
    renderer:
      unsafe: true
